/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.kaltura.kdpfl.dummy.testcase1;
	
	import flash.display.Sprite;
	import com.kaltura.kdpfl.dummy.testcase2;
	import com.kaltura.kdpfl.DummySuit;
	
	public class FlexUnitCompilerApplication extends Sprite {
		private var com_kaltura_kdpfl_DummySuit_obj:com.kaltura.kdpfl.DummySuit;
		private var com_kaltura_kdpfl_dummy_testcase2_obj:com.kaltura.kdpfl.dummy.testcase2;
		
		
		private var com_kaltura_kdpfl_testcase1_obj:com.kaltura.kdpfl.dummy.testcase1;
	}
}