package com.kaltura.vo
{
	import com.kaltura.vo.BaseFlexVo;
	[Bindable]
	public dynamic class KalturaStatsEvent extends BaseFlexVo
	{
		/** 
		* 		* */ 
		public var clientVer : String;

		/** 
		* 		* */ 
		public var eventType : int = int.MIN_VALUE;

		/** 
		* the client's timestamp of this event
		* */ 
		public var eventTimestamp : Number = NaN;

		/** 
		* a unique string generated by the client that will represent the client-side session: the primary component will pass it on to other components that sprout from it		* */ 
		public var sessionId : String;

		/** 
		* 		* */ 
		public var partnerId : int = int.MIN_VALUE;

		/** 
		* 		* */ 
		public var entryId : String;

		/** 
		* the UV cookie - creates in the operational system and should be passed on ofr every event 		* */ 
		public var uniqueViewer : String;

		/** 
		* 		* */ 
		public var widgetId : String;

		/** 
		* 		* */ 
		public var uiconfId : int = int.MIN_VALUE;

		/** 
		* the partner's user id 		* */ 
		public var userId : String;

		/** 
		* the timestamp along the video when the event happend 		* */ 
		public var currentPoint : int = int.MIN_VALUE;

		/** 
		* the duration of the video in milliseconds - will make it much faster than quering the db for each entry 		* */ 
		public var duration : int = int.MIN_VALUE;

		/** 
		* will be retrieved from the request of the user 		* */ 
		public var userIp : String;

		/** 
		* the time in milliseconds the event took		* */ 
		public var processDuration : int = int.MIN_VALUE;

		/** 
		* the id of the GUI control - will be used in the future to better understand what the user clicked		* */ 
		public var controlId : String;

		/** 
		* true if the user ever used seek in this session 		* */ 
		public var seek : Boolean;

		/** 
		* timestamp of the new point on the timeline of the video after the user seeks 		* */ 
		public var newPoint : int = int.MIN_VALUE;

		/** 
		* the referrer of the client		* */ 
		public var referrer : String;

		/** 
		* will indicate if the event is thrown for the first video in the session		* */ 
		public var isFirstInSession : Boolean;

		/** 
		* a list of attributes which may be updated on this object 
		* */ 
		public function getUpdateableParamKeys():Array
		{
			var arr : Array;
			arr = new Array();
			arr.push('clientVer');
			arr.push('eventType');
			arr.push('eventTimestamp');
			arr.push('sessionId');
			arr.push('partnerId');
			arr.push('entryId');
			arr.push('uniqueViewer');
			arr.push('widgetId');
			arr.push('uiconfId');
			arr.push('userId');
			arr.push('currentPoint');
			arr.push('duration');
			arr.push('processDuration');
			arr.push('controlId');
			arr.push('seek');
			arr.push('newPoint');
			arr.push('referrer');
			arr.push('isFirstInSession');
			return arr;
		}

		/** 
		* a list of attributes which may only be inserted when initializing this object 
		* */ 
		public function getInsertableParamKeys():Array
		{
			var arr : Array;
			arr = new Array();
			return arr;
		}

	}
}
